version: '2'
services:
  disconf_redis_1: 
    image: daocloud.io/library/redis
    restart: always
  disconf_redis_2: 
    image: daocloud.io/library/redis
    restart: always
  disconf_zookeeper: 
    image: zookeeper:3.3.6
    restart: always
  disconf_mysql: 
    image: uniquedawn/disconf_mysql:0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: lm1234
    restart: always
  disconf_web: 
    image: uniquedawn/disconf_web:0.0.1
    links: 
      - disconf_redis_1:redis001 
      - disconf_redis_2:redis002
      - disconf_zookeeper:zk_host
      - disconf_mysql:disconf_db
    restart: always
  disconf_nginx: 
    image: uniquedawn/disconf_nginx:0.0.1
    links: 
      - disconf_web:tomcathost 
    ports: 
      - "8282:80" 
    restart: always